const SUCCESS = "SUCCESS";
const FAIL = "FAIL";
const HOST = 'http://169.254.32.117:5001';

const TOKEN_STORAGE_KEY = 'TOKEN_STORAGE_KEY';

const MUSIC_SEARCH_STORAGE_KEY = 'MUSIC_SEARCH_STORAGE_KEY';

const LOOP_STORAGE_KEY = 'LOOP_STORAGE_KEY'; // 音乐循环播放模式

const MUSIC_STORAGE_KEY = 'MUSIC_STORAGE_KEY'; // 当前播放的音乐

const MUSIC_LIST_STORAGE_KEY = 'MUSIC_LIST_STORAGE_KEY'; // 音乐列表

const MUSIC_CLASSIFY_NAME_STORAGE_KEY = 'MUSIC_CLASSIFY_NAME_STORAGE_KEY'; // 音乐分类的名称

const MUSIC_FAVORITE_NAME = 'MUSIC_FAVORITE_NAME'; // 音乐收藏夹名称

const MAX_FAVORITE_NUMBER = 500; // 收藏夹最大数量

const PAGE_SIZE = 20;// 每页数量

const MUSIC_SEARCH_NAME = 'MUSIC_SEARCH_NAME';// 音乐搜查