class ThemeSize {
  static double containerPadding = 15;// 每个模块之间的内边距和外边距
  static double columnPadding = 20;// 上下边距
  static double middleRadius = 10;// 圆角大小
  static double textareaHeight = 150;// 多行文本框的高度
  static double bigRadius = 20;// 圆角大小
  static double superRadius = 30;// 加大版圆角
  static double minBtnRadius = 5;// 小圆角
  static double middleBtnWidth = 70;// 中等按钮宽度
  static double middleBtnHeight = 35;// 中等按钮高度
  static double swiperHeight = 200; // 轮播高度
  static double movieWidth = 150; // 电影图片宽度
  static double movieHeight = 200;// 电影图片高度
  static double modualHeight = 250;// 模块的高度
  static double bigIcon = 40;// 大图标
  static double middleIcon = 30;// 中等图标
  static double playIcon = 25;// 中等图标
  static double navigationIcon = 30;// 导航图标
  static double smallIcon = 20;// 中等图标
  static double miniIcon = 15;// 超小图片
  static double smallMargin = 10;//小边距
  static double miniMargin = 5;// 超小边距
  static double smallFontSize = 14;//常规字体
  static double middleFontSize = 16;//常规字体
  static double bigFontSize = 20;// 大标题字体
  static double smallAvater = 30;// 小头像
  static double middleAvater = 40;// 中等头像
  static double bigAvater = 60;// 大头像
  static double borderWidth = 1;// 边框大小
  static double buttonHeight = 40;//按钮大小
  static int crossAxisCount = 5;// 网格布局每行元素个数
  static double childAspectRatio = 1.6;// 网格布局宽高比例
  static int pageSize = 20;// 每页显示大小
  static double minPlayIcon = 80;// 音乐播放器圈圈大小
  static double menuWidth = 180;// 弹出点赞和评论菜单的宽度
  static double menuHeight = 40;// 弹出点赞和评论菜单的高度
}